# -*- coding: utf-8 -*-
"""变异检查:每条检查都要能失败。

在工作区的一份临时拷贝里,一次改坏一处(脚本里的一个判断、skill 里的一行、AGENTS.md / 设置里的一条),
跑盯着它的那几个测试,应当变红;再还原,下一处。工作区本身一个字节都不动,拷贝最后删掉。
拷贝放在工作区的 .yz-tmp/ 里(不用系统临时文件夹:Codex 沙盒写不进去,和脚本用的是同一条规矩)。

用法(在工作区根目录下跑):
  py -X utf8 tests/mutation_check.py            全部跑一遍,打印每一处的结果;全部变红 → 退出码 0
  py -X utf8 tests/mutation_check.py M03 M17    只跑这几处
"""
import hashlib
import io
import os
import secrets
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURES = os.path.join(ROOT, "tests", "fixtures", "example")
COPY = ("agent-tools", ".agents", ".codex", "wording", "toolkit", "tests", "AGENTS.md", ".gitignore")

C = "agent-tools/card.py"
W = "agent-tools/wording_check.py"
P = "agent-tools/progress.py"
J = "agent-tools/projects.py"
Y = "agent-tools/yzlib.py"
V = "agent-tools/view.py"
TC = "tests/test_card.py::"
TCF = "tests/test_card_fixes.py::"
TP = "tests/test_progress.py::"
TSP = "tests/test_status_page.py::"
TS = "tests/test_skills.py::"
TW = "tests/test_wording.py::"
TV = "tests/test_view.py::"
TE = "tests/test_env.py::"
TPN = "tests/test_pane.py::"
TR3 = "tests/test_round3.py::"
R = "agent-tools/review.py"
L = "agent-tools/liveness.py"
F = "agent-tools/fetches.py"
E = "agent-tools/env_check.py"
RD = "toolkit/scripts/render_docx.py"
RH = "toolkit/scripts/render_html.py"
CC = "toolkit/scripts/cite_check.py"
RA = "toolkit/scripts/refs_add.py"
TR4 = "tests/test_round4.py::"
TR5 = "tests/test_round5.py::"
A = "agent-tools/archive.py"
H = "agent-tools/hook.py"
SE = "agent-tools/sessions.py"
TR6 = "tests/test_round6.py::"
TR7 = "tests/test_round7.py::"
TR8 = "tests/test_round8.py::"
HAN_RANGE = chr(0x4E00) + "-" + chr(0x9FFF)

# (编号, 改坏什么, [(文件, 原文, 改成)], [盯着它的测试])
MUTATIONS = [
    # ---- 第一阶段就有的
    ("M01", "跳过 {} 被当成认不出", [(C, 'if not answers:\n            return "skipped", None', 'if not answers:\n            return "unclear", None')],
     [TC + "test_answer_skipped_writes_no_record_and_logs_skipped"]),
    ("M02", "卡上写的意见被当成确认", [(C, 'approved = chosen is not None and chosen["key"] in ("confirm", "deliver")',
                                   'approved = chosen is None or chosen["key"] in ("confirm", "deliver")')],
     [TC + "test_answer_typed_note_is_not_yet_and_writes_no_record"]),
    ("M03", "字数上限不查", [(C, "if text_len(v) > cap:", "if text_len(v) > cap * 10:")], [TC + "test_refuse_over_length_then_ok"]),
    ("M04", "三点不齐也出卡", [(C, "    problems, _notes, items = pl.commitment_problems(body, whole=whole, line_offset=offset)\n    if problems:",
                              "    problems, _notes, items = pl.commitment_problems(body, whole=whole, line_offset=offset)\n    if False:")],
     [TC + "test_refuse_incomplete_points_then_ok"]),
    ("M05", "交付门槛不看必须改", [(C, 'elif review["counts"]["must_fix"] != 0:', "elif False:")],
     [TC + "test_refuse_delivery_when_must_fix_open_then_ok"]),
    ("M06", "交付门槛不看复核是否对着当前成稿", [(C, "                if not ok:\n                    problems.append(\"独立复核结果对不上当前成稿",
                                                "                if False:\n                    problems.append(\"独立复核结果对不上当前成稿")],
     [TC + "test_refuse_delivery_when_review_is_not_for_current_draft_then_ok"]),
    ("M07", "交付门槛不看交付前检查", [(C, "if rc != 0 or report is None:", "if False:")],
     [TC + "test_refuse_delivery_when_checks_fail_then_ok"]),
    ("M08", "改流程卡不核只改了流程", [(C, "    if matched is None:\n        raise Refuse([\"这一版不只改了流程", "    if False:\n        raise Refuse([\"这一版不只改了流程")],
     [TC + "test_refuse_flow_change_that_changes_more_than_flow_then_ok"]),
    ("M09", "引用的原话不核", [(W, 'return len(said.replace(" ", "")) >= 2 and any(contains_quote(k, said) for k in keys)', "return True")],
     [TC + "test_refuse_quote_not_from_user_then_ok"]),
    ("M10", "用词检查不扫", [(W, '    for mt in d["matchers"]:', '    for mt in d["matchers"][:0]:')],
     [TC + "test_refuse_banned_wording_with_user_term_then_ok", TS + "test_user_facing_spans_pass_the_wording_check"]),
    ("M11", "不要求自报项目外的文件", [(C, 'if "outside" not in fields:', "if False:"),
                                   (C, 'items = fields.get("outside")', 'items = fields.get("outside", [])')],
     [TC + "test_refuse_missing_outside_self_report_then_ok"]),
    ("M12", "出卡时就写了确认记录", [(C, "    yzlib.append_jsonl(log_path, event)\n    out = {",
                                  "    yzlib.append_jsonl(log_path, event)\n    if project and kind in DOC_OF:\n"
                                  "        yzlib.run_toolkit(\"stamp.py\", [os.path.join(project, DOC_OF[kind]), \"--approve\", \"--by\", \"用户\", \"--quote\", \"x\"])\n    out = {")],
     [TC + "test_no_answer_no_record"]),
    ("M13", "用户看卡期间材料变了照样签", [(C, 'same = (not problem) and pl.content_hash(meta, body) == data.get("content_hash")', "same = True")],
     [TC + "test_changed_material_is_not_signed"]),
    ("M14", "选项框返回多个字符串时取第一个", [(C, "    if len(lst) == 1:\n        m = USER_NOTE_RE.match(lst[0])", "    if len(lst) >= 1:\n        m = USER_NOTE_RE.match(lst[0])")],
     [TC + "test_answer_unknown_shapes_are_unclear_and_stored_raw"]),
    ("M15", "回数字不认", [(C, "    idx, how = match_option(s, options, allow_number=True)", "    idx, how = match_option(s, options, allow_number=False)"),
                          (C, "    m = LEAD_NUMBER_RE.match(s)", "    m = None")],
     [TC + "test_text_card_mode"]),
    ("M16", "文字卡模式开关不认", [(C, 'if env in ("text", "native"):', 'if env in ("native",):')], [TC + "test_text_card_mode"]),
    ("M17", "进度页构成条读屏文字的卡片数多数一张", [(P, '"%s %d" % (word, n))', '"%s %d" % (word, n + 1))')], [TP + "test_s3_card_numbers_match_the_files"]),
    ("M17b", "进度页图例的卡片数多数一张", [(P, "esc(word), n))", "esc(word), n + 1))")], [TP + "test_s3_card_numbers_match_the_files"]),
    ("M18", "省掉的环节不显示本项目不需要", [(P, '<span class="meta">本项目不需要</span>', '<span class="meta">未开始</span>')],
     [TP + "test_flow_without_outline_shows_not_needed"]),
    ("M19", "进度页不自己刷新", [(P, '"<meta http-equiv=\\"refresh\\" content=\\"15\\">\\n"', '""')],
     [TP + "test_every_stage_makes_a_full_page_with_the_right_headline"]),
    ("M20", "快照带了 doctype", [(P, "f.write(render_fragment(m, root_id))", 'f.write("<!doctype html>" + render_fragment(m, root_id))')],
     [TP + "test_snapshot_is_a_fragment_with_a_unique_root_and_a_visualize_line"]),
    ("M21", "研究范围那一格不显示", [(P, '("研究范围", panel["scope"])', '("研究范围", None)')],
     [TP + "test_s1_three_things_come_from_task_plan", TP + "test_s0b_three_things_come_from_clarify_note"]),
    ("M22", "skill 里出现 --approve", [(".agents/skills/yunzhi/SKILL.md", "## 对用户说话", "改坏:`stamp.py --approve`\n\n## 对用户说话")],
     [TS + "test_no_client_only_mechanisms"]),
    ("M23", "skill 里命令的路径没加引号", [(".agents/skills/yunzhi/SKILL.md", '$PY "agent-tools/projects.py" list', "$PY agent-tools/projects.py list")],
     [TS + "test_command_paths_are_quoted"]),
    ("M24", "skill 里给用户的话有内部词", [(".agents/skills/yunzhi-card/SKILL.md", "「我没看清你在卡上选的是哪一项，能再说一下吗？」",
                                       "「我没看清你在卡上选的是哪一项（argument 还是 survey），能再说一下吗？」")],
     [TS + "test_user_facing_spans_pass_the_wording_check"]),
    ("M25", "skill 里的卡片示例有内部词", [(".agents/skills/evidence-card/SKILL.md", '"question": "2021 年的分县充电桩数据查不到。增速从哪年开始算？"',
                                         '"question": "闸门触发：2021 年的分县数据查不到。增速从哪年开始算？"')],
     [TS + "test_card_examples_pass_the_same_checks_as_prepare"]),
    ("M26", "同步 skills 时改了换行", [("agent-tools/sync_skills.py", "shutil.copyfile(src[rel], out)",
                                      'open(out, "wb").write(open(src[rel], "rb").read().replace(b"\\n", b"\\r\\n"))')],
     [TS + "test_sync_skills_makes_byte_identical_copies"]),
    ("M27", "空材料被当成转换成功", [(J, "        if not text.strip():\n            return {\"kind\": ext[1:], \"state\": \"empty\"",
                                    "        if False:\n            return {\"kind\": ext[1:], \"state\": \"empty\"")],
     ["tests/test_projects.py::test_new_project_keeps_request_and_reports_four_states"]),
    ("M28", "委托原话没有逐字存", [(J, "        f.write(request_text)", "        f.write(request_text.strip())")],
     ["tests/test_projects.py::test_new_project_keeps_request_and_reports_four_states"]),
    ("M29", "报告类型卡写了意见却当成选了下判断", [(C, '        return {"result": "note", "selected": None,\n                "next": note_only_next("report_type", data, note),',
                                              '        return {"result": "note", "selected": "judge",\n                "next": note_only_next("report_type", data, note),')],
     [TC + "test_report_type_shapes"]),
    ("M30", "认不出改流程卡还在等", [(Y, 'return (isinstance(what, str) and what.startswith(("改流程：", "改流程:"))',
                                    'return (False and isinstance(what, str) and what.startswith(("改流程：", "改流程:"))')],
     ["tests/test_projects.py::test_flow_change_pending_is_reported"]),
    ("M31", "改流程卡的确认选项只写「确认」", [(C, '("confirm", "确认，按新流程走", "以后按这个流程走。")', '("confirm", "确认", "以后按这个流程走。")')],
     [TC + "test_option_labels_are_unique_on_every_card"]),
    ("M32", "AGENTS.md 没写 macOS / Linux 的 $PY", [("AGENTS.md", "macOS / Linux 上 `python3 -X utf8`", "macOS / Linux 上照 Windows")],
     [TS + "test_agents_md_has_no_client_only_mechanisms_and_defines_py"]),
    ("M33", "链接 403 被当成 4xx 失败", [("agent-tools/liveness.py", "if last in (401, 403, 429):", "if last in (401, 429):")],
     ["tests/test_liveness.py::test_states"]),
    ("M34", "交付后不推进到已交付", [(C, '        target = "delivered"', '        target = None')],
     [TC + "test_full_confirm_chain_through_delivery"]),
    ("M35", "确认后不推进到收集资料", [(C, '        target = "collecting"', '        target = None')],
     [TC + "test_answer_picked_option_writes_record_and_advances"]),
    ("M36", "review-module 没写 context: fork", [(".agents/skills/review-module/SKILL.md", "context: fork\n", "")],
     [TS + "test_review_module_runs_in_a_fork_on_workbuddy"]),

    # ---- 第一轮复核(A–M)
    ("A1", "改流程标记回到旧判法(不看确认记录、不看只改了流程)",
     [(Y, "return approval_stale(meta, body) and flow_change_logged(meta) and flow_change_match(meta, body) is not None",
       "return flow_change_logged(meta)")],
     [TSP + "test_status_next_and_page_right_after_flow_change_approval", TCF + "test_flow_change_pending_needs_a_stale_approval"]),
    ("A2", "改流程标记不看「只改了流程」",
     [(Y, "return approval_stale(meta, body) and flow_change_logged(meta) and flow_change_match(meta, body) is not None",
       "return approval_stale(meta, body) and flow_change_logged(meta)")],
     [TSP + "test_flow_change_plus_another_edit_to_the_plan_is_a_real_mismatch"]),
    ("A3", "改流程卡在等时把别的对不上也藏起来",
     [(P, 'consistent = info["consistent"] or bool(info.get("flow_change_pending") and not info.get("other_problems"))',
       'consistent = info["consistent"] or bool(info.get("flow_change_pending"))')],
     [TSP + "test_pending_flow_change_with_another_mismatch_says_stop"]),
    ("A4", "改流程卡在等时不说别的对不上", [(J, 'if info["flow_change_pending"] and info.get("other_problems"):', "if False:")],
     [TSP + "test_pending_flow_change_with_another_mismatch_says_stop"]),
    ("B1", "说明里又把用户原话写在命令行里",
     [("AGENTS.md", 'note-user "<项目名>" --file "projects/<项目名>/records/_inbox.txt"', 'note-user "<项目名>" "<原文>"')],
     [TS + "test_user_messages_go_through_a_file"]),
    ("C1", "卡上不写「右侧已打开 · 点开看」",
     [(C, '            return "（%s · %s）" % (VIEW_OPEN, where)', '            return ""')],
     [TCF + "test_confirm_cards_open_the_material_and_link_it"]),
    ("C2", "材料页的章节名不换成研究员的说法", [(V, "            name = SECTION_NAMES.get(anchor, text)", "            name = text")],
     [TV + "test_task_plan_page_uses_researcher_section_names"]),
    ("C3", "材料页照写资料卡片编号", [(V, "    t = CARD_ID_RE.sub(card, t)\n", "")],
     [TV + "test_dossier_page_shows_card_titles_not_numbers"]),
    ("C4", "答完卡不把右侧那一页换回进度页",
     [(C, '        out.update(yzlib.pane_info(project, out["progress_page"], "progress"))', "        pass")],
     [TCF + "test_answer_puts_the_progress_page_back"]),
    ("D1", "认不出的回答不关卡", [(Y, 'CARD_CLOSED = ("answered", "skipped", "changed", "unclear", "error")',
                                 'CARD_CLOSED = ("answered", "skipped", "changed", "error")')],
     [TCF + "test_unclear_answer_closes_the_card"]),
    # 第五轮:D2 原来拦「原生卡上回数字也算选项」;10-04 实测原生卡的选项有编号,数字本来就该算 —— 反过来拦
    ("D2", "原生卡上手写的数字不算选项", [(C, "    idx, how, typed_note = read_reply(text, options)\n",
                                       "    idx, how, typed_note = read_reply(text, options) if shape == \"chat\" else (match_option(text, options, allow_number=False) + (None,))\n")],
     [TCF + "test_numbers_count_on_native_and_text_cards"]),
    ("D3", "--mode text 不起作用", [(C, '    if override == "text":\n', '    if False:\n')],
     [TCF + "test_numbers_count_on_native_and_text_cards"]),
    ("E1", "两个选项能叫同一个名字", [(C, "            if s in owner and owner[s] is not o:", "            if False:")],
     [TCF + "test_bad_option_labels_are_refused"]),
    ("E2", "选项名可以写「跳过」", [(C, "    if folded in SKIP_WORDS:\n        out.append", "    if False:\n        out.append")],
     [TCF + "test_bad_option_labels_are_refused"]),
    ("E3", "选项名可以只写一个数字", [(C, "    if _NUMBER_RE.fullmatch(folded):\n        out.append", "    if False:\n        out.append")],
     [TCF + "test_bad_option_labels_are_refused"]),
    ("F1", "资料卡片变了照样签资料汇编", [(C, 'same = cards_digest(project) == data.get("cards_digest")', "same = True")],
     [TCF + "test_dossier_card_not_signed_when_cards_change"]),
    ("F2", "交付的三点变了照样交付",
     [(C, 'same = gate["files"] == data.get("files") and gate.get("commitments_digest") == data.get("commitments_digest")',
       'same = gate["files"] == data.get("files")')],
     [TCF + "test_delivery_card_not_signed_when_points_change"]),
    ("G1", "写确认记录失败记成「回答了」", [(C, 'if out["result"] in ("changed", "error"):', 'if out["result"] == "changed":')],
     [TCF + "test_failed_stamp_is_logged_as_error_and_kept_off_the_page"]),
    ("H1", "三点里的引文不核",
     [(C, '"data": data, "scan": scan, "quotes": [(k, v, False) for k, v in scan.items()],', '"data": data, "scan": scan, "quotes": [],')],
     [TCF + "test_fake_quote_in_points_is_refused_then_real_quote_passes"]),
    ("I1", "项目外文件名里的内部词照写", [(C, "    if wording_check.scan(stem, utexts):\n        return OUTSIDE_GENERIC", "    if False:\n        return OUTSIDE_GENERIC")],
     [TCF + "test_outside_files_show_a_human_name"]),
    ("I2", "提纲卡上列的节名不扫", [(C, '        scan["没有资料卡片支撑的节 %d" % (i + 1)] = t or _id', "        pass")],
     [TCF + "test_unsupported_section_titles_on_outline_card_are_scanned"]),
    ("I3", "进度页上的内部词不报", [(P, "    if hits:\n        out[\"page_wording\"]", "    if False:\n        out[\"page_wording\"]")],
     [TSP + "test_internal_words_from_materials_on_the_page_are_reported"]),
    ("J1", "不去掉 U+034F", [(W, "_INVISIBLE_EXTRA = {0x034F, ", "_INVISIBLE_EXTRA = {")],
     [TW + "test_invisible_characters_do_not_hide_a_term"]),
    ("J2", "不去掉 Cf 类字符(标签字符、U+206A…)", [(W, 'return (unicodedata.category(ch) == "Cf" or', "return (False or")],
     [TW + "test_invisible_characters_do_not_hide_a_term"]),
    ("J3", "连字符不归一", [(W, "_DASH = {0x2010, 0x2011, 0x2012, 0x2013, 0x02D7, 0x2796}", "_DASH = set()")],
     [TW + "test_dash_variants_are_folded"]),
    ("J4", "网址吞掉后面的中文", [(W, '"(?:https?://[^%s%s]+|file:[^%s]+)" % (_URL_STOP, _HAN_CLASS, _URL_STOP)',
                                 '"(?:https?://[^%s]+|file:[^%s]+)" % (_URL_STOP, _URL_STOP)')],
     [TW + "test_url_stops_where_chinese_starts"]),
    ("J5", "引文可以切断英文单词", [(W, "    first = bool(_ALNUM_RE.match(needle[0]))\n    last = bool(_ALNUM_RE.match(needle[-1]))",
                                   "    first = False\n    last = False")],
     [TW + "test_quote_must_be_a_whole_span_in_one_message"]),
    ("J6", "引用块不先整块比", [(W, '        if j - i > 1 and verified("\\n".join(_body_of(l) for l in lines[i:j]), keys):', "        if False:")],
     [TW + "test_quote_block_is_checked_as_a_whole_first"]),
    ("J7", "资料卡片编号不算内部词", [("wording/banned-terms.json", r'"re": "S\\d{2,3}"', r'"re": "S\\d{9}"')],
     [TW + "test_fork_terms_are_flagged"]),
    ("K1", "交付的三点没写也显示等你确认交付", [(P, 'x = "w" if c == "d" and r == "d" and points else ""', 'x = "w" if c == "d" and r == "d" else ""')],
     [TSP + "test_no_waiting_for_delivery_without_the_delivery_points"]),
    ("K2", "提醒算成通过", [(C, '    phrase = "%d / %d 通过" % (checks["pass"], checks["total"])',
                            '    phrase = "%d / %d 通过" % (checks["pass"] + checks.get("warn", 0), checks["total"])')],
     [TSP + "test_warnings_are_not_counted_as_passed"]),
    ("K3", "成稿文件不在也说复核之后又改过", [(P, 'elif rev and rev.get("readable") and rev.get("no_files"):', "elif False:")],
     [TSP + "test_missing_out_folder_is_not_called_changed_after_review"]),
    ("L1", "出卡记录坏了也照读", [(C, "    bad = prepared_problems(prepared)\n", "    bad = []\n")],
     [TCF + "test_malformed_prepared_line_gives_a_clean_error"]),
    ("L2", "第二张交付卡又记一次", [(C, 'if kind == "delivery" and state != "verifying":', "if False:")],
     [TCF + "test_second_open_delivery_card_does_not_record_again"]),
    ("L3", "第二张改流程卡又记一次",
     [(C, 'if kind == "flow_change" and (state not in ("collecting", "gate2_awaiting") or not yzlib.flow_change_pending(plan_meta, plan_body)):',
       "if False:")],
     [TCF + "test_second_open_flow_change_card_does_not_record_again"]),
    ("L4", "脚本出错时只有报错栈", [(Y, "    except Exception as e:  # noqa: BLE001  脚本内部出错", "    except ZeroDivisionError as e:  # noqa: BLE001  脚本内部出错")],
     [TCF + "test_internal_errors_print_json_not_a_traceback"]),
    ("V1", "卡上又写「我读过」", [(C, 'OUTSIDE = "这一轮读过的项目以外的文件（助手自报）"', 'OUTSIDE = "这一轮我读过的项目以外的文件（助手自报）"')],
     [TCF + "test_fixed_card_text_never_says_wo"]),
    ("S1", "快照写进项目文件夹", [(C, "    if yzlib.inside_protected(snapshot_dir):\n", "    if False:\n")],
     [TCF + "test_snapshot_is_never_written_inside_a_project"]),
    ("S2", "progress.py 往项目里写快照", [(P, "    if yzlib.inside_protected(out_dir):\n", "    if False:\n")],
     [TCF + "test_snapshot_is_never_written_inside_a_project"]),

    # ---- 第二轮复核(端到端实测)
    ("R2", "临时文件夹又用系统的 mkdtemp", [(Y, "    import secrets\n", "    import secrets\n    import tempfile\n    return tempfile.mkdtemp(prefix=prefix)\n")],
     [TE + "test_no_agent_tool_uses_system_temp_dirs"]),
    ("R1a", "沙盒改回默认", [(".codex/config.toml", 'sandbox = "unelevated"', 'sandbox = "elevated"')], [TE + "test_project_codex_config"]),
    ("R4", "文档插件没关", [(".codex/config.toml", '[plugins."documents@openai-primary-runtime"]\nenabled = false',
                            '[plugins."documents@openai-primary-runtime"]\nenabled = true')], [TE + "test_project_codex_config"]),
    ("R4b", "记忆没关", [(".codex/config.toml", "memories = false", "memories = true")], [TE + "test_project_codex_config"]),
    ("R9", "没开联网", [(".codex/config.toml", "network_access = true", "network_access = false")], [TE + "test_project_codex_config"]),
    ("R5", "AGENTS.md 没写用 UTF-8 读文件", [("AGENTS.md", "Get-Content -Raw -Encoding utf8", "Get-Content -Raw")],
     [TS + "test_agents_md_rules_from_the_end_to_end_run"]),
    ("R8", "新建项目不建 out/", [(J, '("out",), ("review",), ("library",), (yzlib.FETCHED', '("review",), ("library",), (yzlib.FETCHED')],
     [TSP + "test_new_project_creates_standard_folders"]),
    ("R12a", "回答卡片时把 note-user 记过的那句再记一遍",
     [(C, '        if in_scope and isinstance(obj.get("text"), str) and obj["text"].strip() == text:\n            matches.append((i, obj))',
       "        pass")],
     [TCF + "test_user_messages_are_stripped_and_not_doubled", TR8 + "test_note_only_reply_is_logged_once_with_via_and_card"]),
    ("R12c", "用户连着发一样的话被吞(又按字去重)",
     [(C, "    path = yzlib.message_log(project)\n    if card_id and _mark_logged_reply(",
       "    path = yzlib.message_log(project)\n    _m = yzlib.read_jsonl(path)\n    if _m and _m[-1].get(\"text\") == t:\n        return False\n    if card_id and _mark_logged_reply(")],
     [TCF + "test_user_messages_are_stripped_and_not_doubled"]),
    ("R12b", "用户消息带着换行存", [(C, '    t = (text or "").strip()\n    if not t:\n        return False', '    t = text or ""\n    if not t:\n        return False')],
     [TCF + "test_user_messages_are_stripped_and_not_doubled"]),
    ("R14a", "综述型也说「支持判断 / 不支持」", [(C, '    if genre == "survey":\n        return [(pl.STANCE_LABELS["mixed"]', '    if False:\n        return [(pl.STANCE_LABELS["mixed"]')],
     [TCF + "test_survey_dossier_card_uses_neutral_wording", TSP + "test_survey_page_uses_neutral_card_wording"]),
    ("R14b", "成稿的参考文献又写「A级」", [("toolkit/scripts/render_html.py", '        return "官方一手"', '        return "一手(A级)"')],
     [TV + "test_toolkit_renderers_use_user_wording"]),
    ("R15", "约数又被加减", [(".agents/skills/task-planner/SKILL.md", "「两千字左右」写 2000", "「两千字左右」写 2200")],
     [TS + "test_approximate_word_counts_map_to_that_number"]),
    ("R16", "文字卡还说「你点「确认」后」", [(C, "    text_footer = TEXT_FOOTERS.get(footer, footer)\n", "    text_footer = footer\n")],
     [TCF + "test_text_mode_footer_says_reply_1"]),

    # ---- 右侧那一页(10-03 实测:每打开一次右侧就多一个标签 → 一个项目一页,只挂一次,脚本换内容)
    ("P1", "右侧那一页不自己刷新",
     [(Y, r"""'\n<meta http-equiv="refresh" content="%d">' % pane_refresh(kind),""", r"""'\n<!-- %d -->' % pane_refresh(kind),""")],
     [TPN + "test_progress_pane_is_written_atomically_with_a_5s_refresh", TPN + "test_view_pane_shows_the_material_with_links_that_still_work"]),
    ("P2", "右侧那一页不原子写、直接写目标",
     [(Y, "    return write_atomic(pane_path(project), pane_html(page, source_path, kind))",
       '    io.open(pane_path(project), "w", encoding="utf-8", newline="\\n").write(pane_html(page, source_path, kind))\n'
       "    return pane_path(project)")],
     [TPN + "test_progress_pane_is_written_atomically_with_a_5s_refresh"]),
    ("P3", "换名失败时留下临时文件",
     [(Y, "        if os.path.exists(tmp):\n            try:\n                os.remove(tmp)", "        if False:\n            try:\n                os.remove(tmp)")],
     [TPN + "test_a_failed_swap_leaves_the_old_pane_whole_and_no_temp_files"]),
    ("P4", "材料页的相对地址照搬进右侧",
     [(Y, '    text = _ATTR_URL_RE.sub(absolute, _REFRESH_RE.sub("", page))', '    text = _REFRESH_RE.sub("", page)')],
     [TPN + "test_view_pane_shows_the_material_with_links_that_still_work"]),
    ("P5", "右侧那一页还带着进度页自己 15 秒的刷新",
     [(Y, '    text = _ATTR_URL_RE.sub(absolute, _REFRESH_RE.sub("", page))', "    text = _ATTR_URL_RE.sub(absolute, page)")],
     [TPN + "test_progress_pane_is_written_atomically_with_a_5s_refresh"]),
    ("P6", "进度页更新时右侧不跟", [(P, '    if yzlib.pane_kind(project) == "progress":', "    if False:")],
     [TPN + "test_pane_follows_the_progress_page_but_never_covers_a_material"]),
    ("P7", "进度页更新时把右侧的材料盖掉", [(P, '    if yzlib.pane_kind(project) == "progress":', "    if True:")],
     [TPN + "test_pane_follows_the_progress_page_but_never_covers_a_material"]),
    ("P8", "出确认卡不把材料换进右侧",
     [(C, '        out.update(yzlib.pane_info(project, view_page["page"], "view:%s" % view_page["kind"]))', "        pass")],
     [TPN + "test_every_confirm_card_puts_its_material_in_the_pane", TCF + "test_confirm_cards_open_the_material_and_link_it"]),
    ("P9", "新建、接着做、改名不把进度页换进右侧",
     [(J, '    out.update(yzlib.pane_info(project, out["progress_page"], "progress"))', "    pass")],
     [TPN + "test_new_status_and_rename_put_progress_in_the_pane"]),
    ("P10", "skill 里换页面又去打开右侧",
     [(".agents/skills/yunzhi-card/SKILL.md", "**发卡**，看输出里的 `mode`：",
       "先调 `mcp__codex_app__open_in_codex` 把 view_url 挂到右侧。\n\n**发卡**，看输出里的 `mode`：")],
     [TPN + "test_skills_open_the_pane_exactly_once_and_only_on_first_open", TS + "test_card_skill_opens_the_material_and_brings_the_progress_page_back"]),
    ("P11", "挂右侧不再限于这个对话里第一次",
     [(".agents/skills/yunzhi-progress/SKILL.md", "  1. 这个对话里第一次打开或接着做这个项目", "  1. 每次要换页面的时候")],
     [TPN + "test_skills_open_the_pane_exactly_once_and_only_on_first_open"]),
    ("P12", "脚本又叫 agent 去打开右侧",
     [(J, "按 yunzhi-progress 第 1 节把右侧挂上，地址用 pane_url（只挂这一次）", "调 open_in_codex 把 pane_url 挂到右侧")],
     [TPN + "test_scripts_never_tell_the_agent_to_open_the_pane"]),

    # ---- 右侧整页刷新后回到读到的位置(10-03:长的任务计划、资料汇编每次刷新都跳回顶上,读不下去)
    ("P13", "刷新后不回到读到的位置(node 真跑那一条盯着)", [(Y, "    try { window.scrollTo(0, target); } catch (e) {}\n", "")],
     [TPN + "test_reading_position_is_restored_only_for_the_same_content"]),
    ("P13b", "刷新后不回到读到的位置(静态那一条盯着,没有 node 时靠它)", [(Y, "    try { window.scrollTo(0, target); } catch (e) {}\n", "")],
     [TPN + "test_both_kinds_of_pane_carry_refresh_marker_and_scroll_script"]),
    ("P14", "换了内容还回到旧位置", [(Y, "saved.m === mark && ", "")],
     [TPN + "test_reading_position_is_restored_only_for_the_same_content"]),
    ("P15", "存储用不了时脚本报错",
     [(Y, "  try { store = window.sessionStorage; store.getItem(key); } catch (e) { return; }\n", "  store = window.sessionStorage; store.getItem(key);\n")],
     [TPN + "test_reading_position_is_restored_only_for_the_same_content"]),
    ("P16", "材料的内容标记不随内容变",
     [(Y, 'return "%s@%s" % (kind, hashlib.sha256(part.encode("utf-8")).hexdigest()[:12])', 'return "%s@%s" % (kind, "0" * 12)')],
     [TPN + "test_the_marker_changes_when_the_content_changes"]),
    ("P17", "进度页也 30 秒才刷新", [(Y, 'return PANE_REFRESH_VIEW if str(kind).startswith("view:") else PANE_REFRESH', "return PANE_REFRESH_VIEW")],
     [TPN + "test_progress_pane_is_written_atomically_with_a_5s_refresh"]),
    ("P18", "进度页的标记跟着用时、张数变", [(Y, '    if kind == "progress":\n        m = _NOW_BLOCK_RE.search(page)', '    if False:\n        m = _NOW_BLOCK_RE.search(page)')],
     [TPN + "test_progress_marker_follows_the_step_not_the_minutes"]),
    ("P19", "手里没有记下的位置也接管滚动", [(Y, '  if (saved && typeof saved === "object") {', "  if (true) { saved = saved || {};")],
     [TPN + "test_reading_position_is_restored_only_for_the_same_content"]),
    ("P20", "材料又改回 5 秒刷新", [(Y, "PANE_REFRESH_VIEW = 30", "PANE_REFRESH_VIEW = 5")],
     [TPN + "test_view_pane_shows_the_material_with_links_that_still_work"]),

    # ---- 第三轮(用户在桌面版里完整跑了一遍)
    ("Q1", "复核助手报了见过暗号也照样封存", [(R, "    elif seen:\n", "    elif False:\n")],
     [TR3 + "test_seal_needs_evidence_of_a_clean_reviewer_then_seals"]),
    ("Q2", "交的文件里出现暗号也照样封存", [(R, "    if leaked:\n", "    if False:\n")],
     [TR3 + "test_seal_needs_evidence_of_a_clean_reviewer_then_seals"]),
    ("Q3", "随机码不核(没读这一轮的说明也能封)", [(R, '    if not nonce_matches(record, data.get("nonce")):', "    if False:")],
     [TR3 + "test_seal_needs_evidence_of_a_clean_reviewer_then_seals"]),
    ("Q4", "复核读的文件少了也能封", [(R, "        if want - got:\n", "        if False:\n")],
     [TR3 + "test_seal_needs_evidence_of_a_clean_reviewer_then_seals"]),
    ("Q5", "复核不逐段也能封", [(R, '        if missing:\n            out.append("coverage 少了这几段', '        if False:\n            out.append("coverage 少了这几段')],
     [TR3 + "test_seal_needs_evidence_of_a_clean_reviewer_then_seals"]),
    ("Q6", "复核不抽核原文也能封", [(R, "        if len(set(cards)) < need:", "        if False:")],
     [TR3 + "test_seal_needs_evidence_of_a_clean_reviewer_then_seals"]),
    ("Q7", "交付卡不看复核是怎么封存的", [(C, "                    problems += review_mod.sealed_problems(project, review)", "                    pass")],
     [TR3 + "test_delivery_only_accepts_a_review_sealed_by_review_py"]),
    ("Q8", "原生选项卡上不带三点", [(C, '    if card.get("ask_lines"):\n        question += ', '    if False:\n        question += ')],
     [TR3 + "test_native_card_carries_the_three_points"]),
    ("Q9", "资料汇编列了缺口也不先问用户", [(C, "    if gaps and not gap_decision_valid(project, plan_meta):", "    if False:")],
     [TR3 + "test_dossier_with_gaps_needs_a_decision_since_the_plan_was_confirmed"]),
    ("Q10", "任务计划确认之前的决定也算", [(Y, "        if t0 is not None and (t is None or t <= t0):\n            continue", "        if False:\n            continue")],
     [TR3 + "test_dossier_with_gaps_needs_a_decision_since_the_plan_was_confirmed"]),
    ("Q10b", "决定卡上只写了意见也算选过",
     [(Y, '        if e.get("type") != "answered" or e.get("kind") != "decision" or e.get("choice") in (None, ""):',
       '        if e.get("type") != "answered" or e.get("kind") != "decision":'),
      (Y, '        if e.get("result") not in (None, "selected"):\n            continue\n', "")],
     [TR3 + "test_dossier_with_gaps_needs_a_decision_since_the_plan_was_confirmed"]),
    ("Q11", "取到了的来源不要原文摘录",
     [(C, '        if any(s.get("fetch_state") == "ok" and not _text_ok(s.get("excerpt"), EXCERPT_CAP) for s in srcs):', "        if False:")],
     [TR3 + "test_cards_need_excerpts_directions_and_cited_facts"]),
    ("Q12", "研判型的卡不写和核心判断的关系", [(C, '        if genre == "argument" and not _text_ok(direction, DIRECTION_CAP):', "        if False:")],
     [TR3 + "test_cards_need_excerpts_directions_and_cited_facts"]),
    ("Q13", "支持判断 / 不支持的卡可以没有引用的数据(两道都关掉:第四轮起没有引用数据的卡也会被「没有具体的数」那一道拦下)",
     [(C, '        if stance in ("support", "counter") and not cited:', "        if False:"),
      (C, '        elif stance in ("support", "counter") and not any(has_data_point(f.get("value")) for f in cited):', "        elif False:")],
     [TR3 + "test_cards_need_excerpts_directions_and_cited_facts"]),
    ("Q14", "研判型不写找反面证据的记录", [(C, '        if not good:\n            out.append("资料汇编要写找反面证据的记录', '        if False:\n            out.append("资料汇编要写找反面证据的记录')],
     [TR3 + "test_argument_dossier_needs_a_counter_evidence_search"]),
    ("Q15", "缺口和资料缺口卡对不上也出卡", [(C, "    if gap_states != dossier_states:", "    if False:")],
     [TR3 + "test_gap_cards_and_dossier_gaps_must_agree"]),
    ("Q16", "记过没取到的网址可以不留痕", [(C, '    if lost:\n        out.append("这几个网址记过没取到', '    if False:\n        out.append("这几个网址记过没取到')],
     [TR3 + "test_logged_failed_fetches_must_leave_a_trace_on_a_card"]),
    ("Q17", "资料卡片的定位可以写行号",
     [(C, '            bad = locator_problem(s.get("locator"))\n            if bad:\n                out.append("资料卡片',
       '            bad = None\n            if bad:\n                out.append("资料卡片')],
     [TR3 + "test_line_number_locators_are_refused_on_cards_and_references"]),
    ("Q17b", "参考文献的定位可以写行号", [(C, "    problems += reference_locator_problems(project)", "    pass")],
     [TR3 + "test_line_number_locator_in_references_blocks_delivery"]),
    ("Q18", "卡号只差一个下划线就认不出", [(C, "            near = [v for k, v in answers.items() if _id_key(k) == _id_key(card_id)]", "            near = []")],
     [TR3 + "test_answer_accepts_near_ids_and_a_lone_exact_label", TR3 + "test_near_id_also_carries_a_typed_note"]),
    ("Q18b", "只有一道题、回答正好是选项名也认不出", [(C, "            elif len(answers) == 1:", "            elif False:")],
     [TR3 + "test_answer_accepts_near_ids_and_a_lone_exact_label"]),
    ("Q20", "提纲确认过、没改也要重新确认",
     [(C, '    next_state = "outlining" if with_outline and not outline_ok else "drafting"', '    next_state = "outlining" if with_outline else "drafting"')],
     [TR3 + "test_dossier_reconfirm_keeps_a_valid_outline_and_asks_to_continue"]),
    ("Q21", "资料汇编重新确认还用第一次的问法",
     [(C, '        question = ("资料汇编第 %d 版可以定下来，继续写吗？" if again else "资料汇编第 %d 版可以定下来，开始写吗？") % version',
       '        question = "资料汇编第 %d 版可以定下来，开始写吗？" % version')],
     [TR3 + "test_dossier_reconfirm_keeps_a_valid_outline_and_asks_to_continue"]),
    ("Q21b", "提纲重新确认还用第一次的问法",
     [(C, '("提纲第 %d 版可以定下来，继续写吗？" if again else "提纲第 %d 版可以定下来，开始写吗？")', '("提纲第 %d 版可以定下来，开始写吗？")')],
     [TR3 + "test_outline_reconfirm_wording_fits_the_stage"]),
    ("Q22", "环节用时又从上一个环节最后一次确认算", [(P, "        return firsts.get(kind) or approved_at.get(doc)", "        return approved_at.get(doc)")],
     [TR3 + "test_stage_durations_count_from_the_first_entry"]),
    ("Q23", "提纲 --check 不自查", [(V, "    check = outline_check(project) if args.check else None",
                                  '    check = {"check_ok": True, "check_problems": []} if args.check else None')],
     [TR3 + "test_view_outline_check_shows_each_version_on_the_pane"]),
    ("Q24", "沙盒不能联网也把链接记成失败", [(L, '    offline = bool(web) and all(r[1] == ("failed", "net", None) for r in web)', "    offline = False")],
     [TR3 + "test_liveness_offline_is_unchecked_and_web_tool_pages_stay_reachable"]),
    ("Q25", "不能联网时把助手打开过的那条盖掉", [(L, '        if offline and old.get("via") == WEB_TOOL and state != "gap":', "        if False:")],
     [TR3 + "test_liveness_offline_is_unchecked_and_web_tool_pages_stay_reachable"]),
    ("Q26", "委托原话可以加标题行", [(J, '    if re.match(r"^\\s{0,3}#{1,6}\\s", first):', "    if False:")],
     [TR3 + "test_new_project_keeps_the_request_verbatim_and_refuses_a_title_line"]),
    # 第四轮起 PROGRESS.md 第一行有好几条路去对(答完卡、记进度笔记、刷新进度页):改坏写它的那个函数本身
    ("Q27", "PROGRESS.md 第一行不跟着进度走", [(Y, '    state = state_of_project(project) or "planning"\n    first = ', '    state = "planning"\n    first = ')],
     [TR3 + "test_progress_md_first_line_follows_the_state"]),
    ("Q28", "Word 版作者还是 python-docx", [("toolkit/scripts/render_docx.py", '    props.author = "云织"', "    props.author = props.author")],
     [TR3 + "test_word_version_has_proper_properties_heading_and_reference_details"]),
    ("Q28b", "Word 版参考资料和章不同级", [("toolkit/scripts/render_docx.py", '    doc.add_heading("参考资料", level=1)', '    doc.add_heading("参考资料", level=2)')],
     [TR3 + "test_word_version_has_proper_properties_heading_and_reference_details"]),
    ("Q28c", "Word 版参考资料不写网址", [("toolkit/scripts/render_docx.py", '        if e.get("url"):\n            p.add_run(" · %s" % e["url"])',
                                         '        if False:\n            p.add_run(" · %s" % e["url"])')],
     [TR3 + "test_word_version_has_proper_properties_heading_and_reference_details"]),
    ("Q29", "交付前检查又把客户端那一项算进去", [(C, '    kept = [i for i in items if i.get("check") not in AGENT_SKIP_CHECKS]', "    kept = list(items)")],
     [TR3 + "test_checks_count_leaves_out_the_client_only_item"]),
    ("Q16b", "资料汇编的阅读页不照记录说打不开", [(V, '    if gaps:\n        rows.append(("资料缺口"', '    if False:\n        rows.append(("资料缺口"')],
     [TR3 + "test_logged_failed_fetches_must_leave_a_trace_on_a_card"]),
    ("Q30", "查看页又把查阅日期标成发布于", [(V, '("查阅于 %s" % pl.date_text(s.get("as_of")))', '("发布于 %s" % pl.date_text(s.get("as_of")))')],
     [TR3 + "test_cards_page_labels_the_fetch_date_and_shows_excerpts"]),
    ("Q31", "skill 里起复核助手带上整段对话",
     [(".agents/skills/cite-trace/SKILL.md", '**`fork_turns` 明写 `"none"`**', '**不加 `fork_turns`**')],
     [TR3 + "test_skills_spawn_the_reviewer_without_the_conversation"]),
    ("Q32", "复核的第零层不查停下来问的条件", [(".agents/skills/review-module/SKILL.md", "- **停下来问用户的条件**：", "- **任务计划的其他条件**：")],
     [TR3 + "test_review_zeroth_layer_checks_stop_conditions"]),

    # ---- 第四轮(第三轮复核 + Codex 重跑)
    ("T01", "start 的输出带出了随机码", [(R, '    return {"ok": True, "round": n, "brief":', '    return {"ok": True, "round": n, "nonce": nonce, "brief":')],
     [TR4 + "test_review_start_never_shows_the_nonce_and_asks_for_fork_turns_none"]),
    ("T02", "开始记录又存随机码原文", [(R, '    record = {"round": n, "nonce_sha256":', '    record = {"round": n, "nonce": nonce, "nonce_sha256":')],
     [TR4 + "test_review_start_never_shows_the_nonce_and_asks_for_fork_turns_none"]),
    ("T03", "start 又叫主助手不写 fork_turns", [(R, r'fork_turns 明写 \"none\" —— 这一项不写', r'不加 fork_turns（要写就写 \"none\"） —— 这一项不写')],
     [TR4 + "test_review_start_never_shows_the_nonce_and_asks_for_fork_turns_none"]),
    ("T04", "AGENTS.md 又说不加 fork_turns", [("AGENTS.md", '**`fork_turns` 明写 `"none"`**', "**不加 `fork_turns`**")],
     [TR3 + "test_skills_spawn_the_reviewer_without_the_conversation"]),
    ("T05", "不在工作区根目录也照跑", [(Y, "    problem = cwd_problem()\n    if problem:\n        return emit(", "    problem = None\n    if problem:\n        return emit(")],
     [TR4 + "test_scripts_refuse_to_run_outside_the_workspace_root"]),
    ("T06", "env_check 不说怎么回到工作区根目录", [(E, '    if not where["ok"]:', "    if False:")],
     [TR4 + "test_scripts_refuse_to_run_outside_the_workspace_root"]),
    ("T07", "AGENTS.md 的出错规矩又叫停下来等用户", [("AGENTS.md", "同一步最多自己重试 3 次", "停下来等用户定")],
     [TR4 + "test_agents_stop_rule_fixes_and_retries_without_asking"]),
    ("T08", "没引用的失效链接照样要 ⚠", [(CC, '                  and e["liveness"].get("detail") != "net"\n                  and e.get("id") in cited_ids]',
                                      '                  and e["liveness"].get("detail") != "net"]')],
     [TR4 + "test_uncited_dead_link_does_not_block_and_cited_one_needs_a_mark"]),
    ("T09", "卡片说明里没了 answer 跑完之前不说结果的硬规矩",
     [(".agents/skills/yunzhi-card/SKILL.md", "**在 `answer` 跑完之前，不对用户说结果**", "**先说一句结果，再跑 answer**")],
     [TR4 + "test_card_skill_and_agents_keep_the_first_message_neutral"]),
    ("T10", "不符可以不连着一条必须改", [(R, "                problem = mismatch_finding_problem(row, findings)\n                if problem:",
                                     "                problem = None\n                if problem:")],
     [TR4 + "test_seal_needs_a_must_fix_for_every_mismatch_then_seals"]),
    ("T11", "不符连着的不是必须改也行", [(R, '    if not isinstance(f, dict) or f.get("severity") != "must_fix":', "    if not isinstance(f, dict):")],
     [TR4 + "test_seal_needs_a_must_fix_for_every_mismatch_then_seals"]),
    ("T12", "全写无法验证也能封存", [(R, '        if results and all(r == "无法验证" for r in results):', "        if False:")],
     [TR4 + "test_seal_refuses_all_unverifiable"]),
    ("T13", "direction 的开头和类别不一致也出卡", [(C, "            elif says != stance:", "            elif False:")],
     [TR4 + "test_direction_must_agree_with_the_stance"]),
    ("T14", "direction 的开头认不出也出卡", [(C, "            if says is None:\n", "            if False:\n")],
     [TR4 + "test_direction_must_agree_with_the_stance"]),
    ("T15", "正反证据可以没有具体的数",
     [(C, '        elif stance in ("support", "counter") and not any(has_data_point(f.get("value")) for f in cited):', "        elif False:")],
     [TR4 + "test_support_and_counter_need_a_concrete_data_point"]),
    ("T16", "汉字数目带单位不算具体的数", [(C, "DATA_POINT_RE = re.compile(r\"[0-9０-９]|", "DATA_POINT_RE = re.compile(r\"[0-9０-９]|(?!)")],
     [TR4 + "test_support_and_counter_need_a_concrete_data_point"]),
    ("T17", "方法说明标成不支持也出卡",
     [(C, '            if stance == "counter" and (METHOD_NOTE_RE.match(said) or METHOD_NOTE_RE.match(str(card.get("title") or ""))):',
       "            if False:")],
     [TR4 + "test_method_notes_cannot_be_counter_evidence"]),
    ("T18", "Word 版又丢标题后紧贴的那一段", [(RD, "                i += 1\n                continue\n            # 表可以紧贴在正文行之后",
                                         "                break\n            # 表可以紧贴在正文行之后")],
     [TR4 + "test_word_keeps_the_paragraph_right_after_a_heading"]),
    ("T19", "Word 版的章又从标题 2 起", [(RD, "    shift = (min(levels) - 1) if levels else 0", "    shift = 0")],
     [TR4 + "test_word_time_is_utc_and_headings_start_at_level_1"]),
    ("T20", "Word 版时间又写本地时刻(本机在东部时间才变红)",
     [(RD, "    now = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0, tzinfo=None)",
       "    now = datetime.datetime.now().replace(microsecond=0)")],
     [TR4 + "test_word_time_is_utc_and_headings_start_at_level_1"]),
    ("T21", "各节文内引用数不核", [(CC, "            why = section_cite_mismatch(expected, got)\n            if why:", "            why = None\n            if why:")],
     [TR4 + "test_cross_format_check_counts_citations_per_section"]),
    ("T22", "网页版参考资料对没读到的来源照写查阅于", [(RH, "        if never_read(e):\n            bits.append(", "        if False:\n            bits.append(")],
     [TR4 + "test_refs_add_carries_fetch_state_and_never_read_sources_are_marked"]),
    ("T23", "Word 版参考资料对没读到的来源照写查阅于", [(RD, "        if never_read(e):\n            p.add_run(", "        if False:\n            p.add_run(")],
     [TR4 + "test_refs_add_carries_fetch_state_and_never_read_sources_are_marked"]),
    ("T24", "参考文献清单不带 fetch_state", [(RA, '                    "fetch_state": merged_fetch_state(None, s.get("fetch_state")),\n', "")],
     [TR4 + "test_refs_add_carries_fetch_state_and_never_read_sources_are_marked"]),
    ("T25", "同一网址有一张卡读到了也不算读到", [(RA, '    if old == "ok" or new == "ok":\n        return "ok"', '    if old == "ok":\n        return "ok"')],
     [TR4 + "test_refs_add_merge_rule"]),
    ("T26", "当初没读到、现在打得开的来源不提醒回去读", [(L, '    if retry:\n        out["retry"] = retry', '    if False:\n        out["retry"] = retry')],
     [TR4 + "test_liveness_asks_to_retry_a_source_that_was_never_read"]),
    ("T27", "选项名 + user_note 认不出", [(C, "        if sum(1 for m in notes if m) == 1:", "        if False:")],
     [TR4 + "test_option_plus_user_note_confirms_with_the_note_as_quote", TR4 + "test_note_first_then_label_and_not_yet_with_note",
      TR4 + "test_option_plus_note_on_a_decision_card"]),
    ("T28", "确认记录的原话不用卡上写的意见",
     [(C, '    quote = (note.strip() if note and note.strip() else (chosen["base"] or chosen["label"]))[:QUOTE_CAP]',
       '    quote = (chosen["base"] or chosen["label"])[:QUOTE_CAP]')],
     [TR4 + "test_option_plus_user_note_confirms_with_the_note_as_quote"]),
    ("T29", "选了一项又写的意见不进消息记录", [(C, "    else:\n        words = extra_note\n", "    else:\n        words = None\n")],
     [TR4 + "test_option_plus_user_note_confirms_with_the_note_as_quote"]),
    ("T30", "任务计划再确认一次,同一批缺口的决定作废",
     [(C, "        if isinstance(covered, list) and current <= {str(x) for x in covered}:\n            return True", "        if False:\n            return True")],
     [TR4 + "test_gap_decision_survives_a_later_plan_reapproval_if_it_covers_the_same_gaps"]),
    ("T31", "多出新缺口也算老决定管着", [(C, "current <= {str(x) for x in covered}", "current & {str(x) for x in covered}")],
     [TR4 + "test_gap_decision_survives_a_later_plan_reapproval_if_it_covers_the_same_gaps"]),
    ("T32", "决定卡的回答不记管哪些缺口", [(C, '            event["gap_cards"] = gap_card_uids(project)', "            pass")],
     [TR4 + "test_answer_records_the_gap_cards_a_decision_covers"]),
    ("T33", "记过打不开的网址卡上改写成 ok 也出卡", [(C, "    for uid, url, on_card in relabeled[:4]:", "    for uid, url, on_card in relabeled[:0]:")],
     [TR4 + "test_logged_blocked_url_cannot_be_relabeled_ok_without_a_retry"]),
    ("T34", "fetches 的 ok 什么时候都能记",
     [(F, '        if args.state == "ok" and latest_states(project).get(args.url.strip()) not in FAILED_STATES:', "        if False:")],
     [TR4 + "test_fetches_ok_only_after_a_failure"]),
    ("T35", "后来取到了的网址还算没取到",
     [(F, '        if url and st in FAILED_STATES and latest.get(url) != "ok":', "        if url and st in FAILED_STATES:")],
     [TR4 + "test_logged_blocked_url_cannot_be_relabeled_ok_without_a_retry", TR8 + "test_failed_fetches_are_counted_per_source"]),
    ("T36", "资料缺口卡的情况又把 empty 当成 gap", [(C, '    for st in ("blocked", "failed", "empty"):\n        if st in states:', '    for st in ("blocked", "failed"):\n        if st in states:')],
     [TR4 + "test_a_page_without_the_data_is_called_empty_everywhere"]),
    ("T37", "带页码、表号的行号也拒收", [(C, "    if m and PAGE_TABLE_RE.search(loc):\n        return None", "    if False:\n        return None")],
     [TR4 + "test_locator_rule_accepts_real_positions"]),
    ("T38", "「第3行政区」被当成行号", [(C, "行(?![" + HAN_RANGE + "])\"", "行\"")],
     [TR4 + "test_locator_rule_accepts_real_positions"]),
    ("T39", "进度页刷新不对上 PROGRESS.md 第一行", [(P, "            yzlib.update_progress_md(project)\n        except OSError:", "            pass\n        except OSError:")],
     [TR4 + "test_progress_md_follows_advance_verifying_and_logs_the_dossier_approval"]),
    ("T40", "资料汇编确认了不记进度笔记", [(C, "    yzlib.append_progress_note(project, noted)", "    pass")],
     [TR4 + "test_progress_md_follows_advance_verifying_and_logs_the_dossier_approval"]),
    ("T41", "没挂右侧也写「右侧已打开」", [(C, '        if role == "main" and pane_open:', '        if role == "main":')],
     [TR4 + "test_pane_open_flag_and_text_card_location"]),
    ("T42", "文字卡里又放 file:/// 地址",
     [(C, '        where = ("全文在%s" % readable_place(project, pages[k]) if mode == "text"', '        where = ("全文在%s" % readable_place(project, pages[k]) if False')],
     [TR4 + "test_pane_open_flag_and_text_card_location", "tests/test_cli_flow.py::test_new_project_to_first_confirmation_in_text_card_mode"]),
    ("T43", "答完卡不给对用户说的那一句", [(C, '    out = {"result": "approved", "state": target or state, "next": nexts[kind],\n           "say": approved_say(kind, version, target, data)}',
                                       '    out = {"result": "approved", "state": target or state, "next": nexts[kind]}')],
     [TR4 + "test_card_skill_and_agents_keep_the_first_message_neutral"]),
    # ---- 第五轮(10-04 桌面版 26.930 + GPT-6.1 Sol 实测、命令行全程试跑)
    ("U01", "「数字 + 意见」只认成意见", [(C, "        if ok:\n            if 1 <= n <= len(options):", "        if ok and False:\n            if 1 <= n <= len(options):")],
     [TR5 + "test_reply_reader_accepts"]),
    ("U02", "数字后面紧跟着字也当选项", [(C, "    return False, None\n\n\ndef read_reply(", "    return True, rest.strip()\n\n\ndef read_reply(")],
     [TR5 + "test_reply_reader_rejects"]),
    ("U03", "标点后面紧跟数字也当分隔", [(C, "        if after[:1].isdigit():\n            return False, None", "        if False:\n            return False, None")],
     [TR5 + "test_reply_reader_rejects"]),
    ("U04", "量词前面的空白也当分隔", [(C, "        if stripped[0].isdigit() or stripped[0] in UNIT_AFTER:", "        if False:")],
     [TR5 + "test_reply_reader_rejects"]),
    ("U05", "超出选项数的数字也算", [(C, "            if 1 <= n <= len(options):\n                return n - 1,", "            if 1 <= n:\n                return min(n, len(options)) - 1,")],
     [TR5 + "test_reply_reader_rejects"]),
    ("U06", "选项名 + 意见不认", [(C, "                    if ok and note and (best is None or k > best[0]):", "                    if False:")],
     [TR5 + "test_reply_reader_accepts"]),
    ("U07", "选项名可以用「数字 + 标点」开头", [(C, "    elif re.match(", "    elif False and re.match(")],
     [TR5 + "test_option_labels_cannot_start_with_a_number_and_punctuation"]),
    ("U08", "卡收起来之后不许再答", [(C, '    if last.get("type") == "skipped":\n        return "skipped"', '    if False:\n        return "skipped"')],
     [TR5 + "test_number_after_collapse_answers_the_card_once"]),
    ("U09", "卡收起来之后能答不止一次", [(C, '    if len(closing) != 1:\n        return None\n    last = closing[0]',
                                         '    if not closing:\n        return None\n    last = closing[0]')],
     [TR5 + "test_after_collapse_only_one_more_answer"]),
    ("U10", "收起之后出过别的卡照样算它的回答", [(C, "    if reopen and latest_prepared(log) is not prepared:", "    if False:")],
     [TR5 + "test_after_collapse_a_newer_card_wins"]),
    ("U11", "收起之后认不出的话也当回答", [(C, '    if reopen and (shape not in ("chat", "tool") or read_reply(text, options)[0] is None):', "    if False:")],
     [TR5 + "test_after_collapse_other_messages_are_just_chat"]),
    ("U12", "记用户消息时不提示收起的卡", [(C, "    card, why = reopenable_card(project)", "    card, why = None, None")],
     [TR5 + "test_number_after_collapse_answers_the_card_once"]),
    ("U13", "卡收起来的说法只说点了跳过", [(C, '            else "这张卡先收起来了（你点了跳过，或者太久没操作被自动收起）。")', '            else "好，这张卡先放一边。")')],
     [TR5 + "test_skipped_say_covers_both_cases_and_lists_the_numbers"]),
    ("U14", "卡收起来之后不列选项编号", [(C, 'say = head + ("想好了直接回复选项前面的数字就行：%s。" % numbered if numbered else "想好了直接告诉我。")', 'say = head + "想好了直接告诉我。"')],
     [TR5 + "test_skipped_say_covers_both_cases_and_lists_the_numbers"]),
    ("U15", "原生卡前不提醒会自动收起", [(C, '    if mode != "text":\n        # 第五轮 H2', "    if False:\n        # 第五轮 H2")],
     [TR5 + "test_native_cards_warn_about_auto_collapse_text_cards_do_not"]),
    ("U16", "内部文件的链接不拦", [(W, "        if internal_link_target(m.group(2)):", "        if False:")],
     [TR5 + "test_wording_check_blocks_links_to_internal_files", TR5 + "test_internal_link_on_a_card_is_refused_then_ok"]),
    ("U17", "AGENTS.md 没写不提说明书", [("AGENTS.md", "  - 不提 skill、说明、指引、流程文件、规矩", "  - 可以提 skill")],
     [TR5 + "test_agents_md_forbids_talking_about_the_instructions"]),
    ("U18", "决定卡选了一项不给 say", [(C, ',\n            "say": selected_say("decision", chosen, note)}', "}")],
     [TR5 + "test_scripts_give_say_for_what_the_agent_relays"]),
    ("U19", "推荐项不放第一", [(C, '    options.sort(key=lambda o: 0 if o["key"] == key else 1)', "    pass")],
     [TR5 + "test_recommended_report_type_comes_first_and_numbers_follow", TR5 + "test_recommended_decision_option_comes_first_selected_keeps_field_order"]),
    ("U20", "决定卡的 selected 改按卡上的顺序数", [(C, "    recommended_first(options, None if rec is None else str(rec))\n",
                                                   "    recommended_first(options, None if rec is None else str(rec))\n    for j, o in enumerate(options):\n        o[\"key\"] = str(j + 1)\n")],
     [TR5 + "test_recommended_decision_option_comes_first_selected_keeps_field_order"]),
    ("U21", "项目文件夹不干净也出卡", [(C, "            messy = yzlib.hygiene_problems(project)", "            messy = []")],
     [TR5 + "test_scripts_in_the_project_block_cards_then_ok", TR5 + "test_files_in_inputs_that_the_user_did_not_give_block_cards"]),
    ("U22", "不查 inputs 里没登记的文件", [(Y, "            if rel not in allowed:\n                out.append(rel)", "            if False:\n                out.append(rel)")],
     [TR5 + "test_files_in_inputs_that_the_user_did_not_give_block_cards"]),
    ("U23", "Word 锁文件也挡卡", [(Y, '            if fn.startswith(("~$", ".")) or fn.lower() in SYSTEM_FILES:', "            if False:")],
     [TR5 + "test_word_lock_files_in_inputs_do_not_block_cards"]),
    ("U24", "不查项目里的脚本", [(Y, "            if os.path.splitext(fn)[1].lower() in SCRIPT_EXTS:", "            if False:")],
     [TR5 + "test_scripts_in_the_project_block_cards_then_ok"]),
    ("U25", "交付之后不归档", [(C, "            archived = archive.run(project)", '            archived = {"ok": False, "problems": ["没跑"]}')],
     [TR5 + "test_delivery_runs_the_archive_and_check_passes"]),
    ("U26", "归档核对不查红线候选的文件", [(A, '    lost = [r for r in candidates if not os.path.isfile(library(project, "rules", "%s.md" % r))]', "    lost = []")],
     [TR5 + "test_archive_check_fails_when_the_archive_is_incomplete"]),
    ("U27", "归档核对不查来源", [(A, "        if have != want:", "        if False:")],
     [TR5 + "test_archive_check_fails_when_the_archive_is_incomplete"]),
    ("U28", "没交付也归档", [(A, '    if not isinstance(plan, dict) or plan.get("pipeline_status") != "delivered":\n        return {"ok": False, "problems": ["还没交付',
                              '    if False:\n        return {"ok": False, "problems": ["还没交付')],
     [TR5 + "test_archive_refuses_before_delivery"]),
    ("U29", "取来的资料存进 inputs/", [(F, '    orig_dir = os.path.join(project, yzlib.FETCHED, "originals")', '    orig_dir = os.path.join(project, "inputs", "originals")')],
     [TR5 + "test_fetches_save_stores_and_converts_under_fetched"]),
    ("U30", "网页不转成文字", [(J, "    if ext in HTML_EXTS:", "    if False:")],
     [TR5 + "test_fetches_save_stores_and_converts_under_fetched"]),
    ("U31", "放错在 inputs/ 里的不挪走", [(F, '    moved = _inside(src, os.path.join(project, "inputs"))', "    moved = False")],
     [TR5 + "test_files_in_inputs_that_the_user_did_not_give_block_cards"]),
    ("U32", "先 answer 后 note-user 记两遍", [(C, "    if answered_just_now(project, text):", "    if False:")],
     [TR5 + "test_answer_then_note_user_records_once", TR5 + "test_native_typed_note_then_note_user_records_once"]),
    ("U33", "交付卡前不带篇幅", [(C, '    if size_line:\n        lines.append("- %s" % size_line)', '    if False:\n        lines.append("- %s" % size_line)')],
     [TR5 + "test_delivery_message_carries_counts_read_from_the_files"]),
    ("U34", "篇幅里的文内引用多数一处", [(C, '"citations": int(cells["文内引用"])', '"citations": int(cells["文内引用"]) + 1')],
     [TR5 + "test_delivery_message_carries_counts_read_from_the_files"]),
    ("U35", "委托原话放在共用的 _inbox/ 也收", [(J, "    if yzlib.in_shared_inbox_root(path):", "    if False:")],
     [TR5 + "test_staged_request_must_not_sit_in_the_shared_inbox"]),
    ("U36", "新建项目不收拾暂存文件夹", [(J, "        clean_staging(args.request_file, args.material)", "        pass")],
     [TR5 + "test_new_project_cleans_its_staging_folder"]),
    ("U37", "出卡给的回答文件在共用的 _inbox/", [(C, '    answer_file = yzlib.inbox_file(yzlib.project_name(project) if project else yzlib.PICK_INBOX, "answer.txt")',
                                                 '    answer_file = "projects/_inbox/answer.txt"')],
     [TR5 + "test_card_commands_use_the_project_inbox"]),
    ("U38", "skill 里又要求贴快照", [(".agents/skills/yunzhi-progress/SKILL.md", "生成快照的脚本还留着（以后查清了再打开），但这一版的流程里不走它。",
                                   '最后一步跑 `$PY "agent-tools/progress.py" "<项目名>" --snapshot --out-dir "<可视化目录>"`。')],
     [TS + "test_snapshot_is_paused_in_every_command"]),
    ("U39", "提纲又改回先聊再出卡", [(".agents/skills/outline-cocreate/SKILL.md", "**第一版写好就出提纲卡**", "**用户说可以了再出提纲卡**")],
     [TR5 + "test_outline_skill_cards_the_first_version"]),
    ("U40", "AGENTS.md 没写只用会等回答的选项框", [("AGENTS.md", "，不用 `request_user_input_async`：", "，也可以用 `request_user_input_async`：")],
     [TR5 + "test_only_the_blocking_card_tool"]),
    ("U41", "evidence-card 没写取来的资料放哪", [(".agents/skills/evidence-card/SKILL.md", "存进 `fetched/`，不放进 `inputs/`**", "存进 `inputs/`**")],
     [TR5 + "test_evidence_skill_says_where_fetched_files_go"]),
    ("U42", "接着做的时候不给 say", [(J, '        info["say"] = status_say(info)', "        pass")],
     [TR5 + "test_scripts_give_say_for_what_the_agent_relays"]),
    ("U43", "cite-trace 没说归档用现成的脚本", [(".agents/skills/cite-trace/SKILL.md", "不自己写归档的脚本", "自己写个归档脚本也行")],
     [TR5 + "test_docs_point_to_the_archive_script"]),
    ("U44", "选了「先不确认」又写「好的」也当成想确认", [(C, "    if not approved and chosen is None and note and note.strip()", "    if not approved and note and note.strip()")],
     [TR5 + "test_explicit_not_yet_with_a_yes_word_is_not_looks_like_yes"]),
    # ---- 第六轮(10-04):守门 hooks + 三处小修
    ("X01", "选项卡的参数不核", [(H, "        if is_open and isinstance(ask, dict) and sessions.canon(ask) == want:", "        if is_open:")],
     [TR6 + "test_native_card_must_match_an_open_card"]),
    ("X02", "request_user_input_async 不拦", [(H, '    if low.endswith("request_user_input_async"):\n        return refuse(d, name, ASYNC_REASON)',
                                              '    if False:\n        return refuse(d, name, ASYNC_REASON)')],
     [TR6 + "test_async_input_tool_is_always_refused"]),
    ("X03", "起子助手不核 fork_turns", [(H, '    if isinstance(fork, str) and fork.strip() == "none":', "    if True:")],
     [TR6 + "test_spawn_needs_fork_turns_none"]),
    ("X04", "自己调 stamp.py 写确认记录不拦", [(H, "    if APPROVE_RE.search(cmd):", "    if False:")], [TR6 + "test_shell_rules"]),
    ("X05", "推进到哪个状态不核", [(H, "        if m.group(1) not in AGENT_STATES:", "        if False:")], [TR6 + "test_shell_rules"]),
    ("X06", "用命令写记录文件不拦", [(H, "    if RECORD_RE.search(cmd) and (WRITE_RE.search(cmd) or redirect_targets(cmd)):", "    if False:")],
     [TR6 + "test_shell_rules"]),
    ("X07", "用命令写工具文件不拦", [(H, '        if TOOL_PATH_RE.search(" " + t):\n            return TOOL_REASON % t',
                                    '        if False:\n            return TOOL_REASON % t')], [TR6 + "test_shell_rules"]),
    ("X08", "先 cd 再跑脚本不拦", [(H, "    if CD_RE.search(cmd):\n        return CD_REASON", "    if False:\n        return CD_REASON")],
     [TR6 + "test_shell_rules"]),
    ("X09", "改会话号、云织开关不拦", [(H, "    return ENV_REASON if ENV_SET_RE.search(cmd) else None", "    return None")], [TR6 + "test_shell_rules"]),
    ("X10", "工作目录不是根目录也放行", [(H, "        if not same_dir(os.path.join(base, wd), ROOT):\n            return CD_REASON",
                                      "        if False:\n            return CD_REASON")],
     [TR6 + "test_shell_workdir_other_than_the_root_is_refused_for_scripts"]),
    ("X11", "补丁改受保护的文件不拦", [(H, '            if kind:\n                return refuse(d, "apply_patch", PATCH_PROTECTED_REASON',
                                     '            if False:\n                return refuse(d, "apply_patch", PATCH_PROTECTED_REASON')],
     [TR6 + "test_patch_protected_paths", TR6 + "test_patch_into_the_projects_folder_by_absolute_path"]),
    ("X12", "补丁改确认记录不拦", [(H, '    if approval_sig(old_meta) != approval_sig(new_meta) and "SET" in', '    if False and "SET" in')],
     [TR6 + "test_patch_cannot_write_or_remove_a_confirmation", TR6 + "test_patch_on_an_approved_plan", TR6 + "test_patch_new_task_plan"]),
    ("X13", "补丁把进度改到确认之后不拦", [(H, "        if after != before and after is not None and after not in PLAN_STATES_OK:", "        if False:")],
     [TR6 + "test_patch_cannot_move_the_plan_past_the_confirmation"]),
    ("X14", "补丁套不上时不看加进去的行", [(H, '        if any(APPROVAL_TEXT_RE.match(l) for l in op["lines"]):', "        if False:")],
     [TR6 + "test_patch_that_does_not_apply_falls_back_to_the_added_lines"]),
    ("X15", "确认记录里不加引号的时刻不归一", [(H, "    ap = {k: (v.isoformat() if isinstance(v, date) else v) for k, v in ap.items()}", "    pass")],
     [TR6 + "test_patch_on_an_approved_plan"]),
    ("X16", "最后一条回复不打回", [(H, '    if d.get("stop_hook_active"):', "    if True:")], [TR6 + "test_stop_sends_internal_talk_back_once"]),
    ("X17", "回复里的内部路径不认", [(H, '        if kind == "internal":', "        if False:")], [TR6 + "test_stop_sends_internal_talk_back_once"]),
    ("X18", "回复里说自己说明的词不认", [(W, "    for mt in extra:\n        match(mt)", "    for mt in extra[:0]:\n        match(mt)")],
     [TR6 + "test_stop_sends_internal_talk_back_once"]),
    ("X19", "回复里成稿、「查看」的链接也拦", [(H, '        return "ok"', '        return "other"')],
     [TR6 + "test_stop_negative_controls", TR6 + "test_card_messages_and_says_pass_the_reply_scan"]),
    ("X20", "扫回复时不认用户原话", [(H, "    texts = [p for _t, p in sessions.prompts(session_id)] if session_id else []", "    texts = []")],
     [TR6 + "test_stop_negative_controls"]),
    ("X21", "用户的原话不记", [(H, '    if isinstance(prompt, str):\n        note(d, {"event": "prompt"', '    if False:\n        note(d, {"event": "prompt"')],
     [TR6 + "test_user_prompt_is_recorded_verbatim_and_never_blocks"]),
    ("X22", "卡上交回的原文不记", [(H, '        rec["response"] = found', '        rec["response"] = None')],
     [TR6 + "test_post_tool_use_records_the_native_answer"]),
    ("X23", "守门脚本自己出错就崩", [(H, "        log_error(data)\n        return 0", "        log_error(data)\n        raise")],
     [TR6 + "test_hook_never_blocks_on_its_own_errors"]),
    ("X24", "文字卡模式的卡也放行选项框", [(H, '            if ev.get("mode") == "text":', "            if False:")],
     [TR6 + "test_text_mode_card_cannot_use_the_native_tool"]),
    ("X25", "答过的卡也放行选项框", [(H, '            closed = any(e.get("card_id") == cid and e.get("type") in CARD_CLOSED for e in events[i + 1:])',
                                    "            closed = False")],
     [TR6 + "test_native_card_must_match_an_open_card"]),
    ("X26", "升级前出的卡不提示重出", [(H, '    if any(is_open and not isinstance(ev.get("ask"), dict) for _p, ev, is_open in same):', "    if False:")],
     [TR6 + "test_card_from_before_the_hooks_must_be_prepared_again"]),
    ("X27", "守门脚本把说明里叫跑的命令拦了", [(H, 'AGENT_STATES = ("gate1_awaiting", "gate2_awaiting", "gate3_awaiting", "verifying")',
                                           'AGENT_STATES = ("gate1_awaiting", "gate3_awaiting", "verifying")')],
     [TR6 + "test_every_instructed_command_passes_the_shell_guard"]),
    ("X28", "出卡记录不存 ask", [(C, '"data": card["data"], "fields": fields, "ask": ask}', '"data": card["data"], "fields": fields}')],
     [TR6 + "test_prepared_event_keeps_the_ask_and_a_fine_timestamp", TR6 + "test_native_card_must_match_an_open_card"]),
    ("X29", "对话里的回答不核", [(C, "        if said and any(sessions.norm_text(p) == said for _t, p in sessions.prompts(sid, after=since)):",
                                 "        if True:")],
     [TR6 + "test_chat_answer_must_match_a_prompt_after_the_card"]),
    ("X30", "原生卡的回答不核", [(C, '        if sessions.canon(last["response"]) == sessions.canon(obj):', "        if True:")],
     [TR6 + "test_native_answer_must_match_what_the_card_returned"]),
    ("X31", "没问过的卡也收回答", [(C, '    return "not_asked", HOOK_NOT_ASKED', '    return "unverified", None')],
     [TR6 + "test_native_answer_without_any_record_is_refused"]),
    ("X32", "出卡之前说的话也算回答", [(SE, '        if after is not None and (t is None or t <= after):\n            continue\n        out.append((t, r["prompt"]))',
                                       '        out.append((t, r["prompt"]))')],
     [TR6 + "test_chat_answer_must_match_a_prompt_after_the_card"]),
    ("X33", "守门脚本在跑时引文照旧认助手记的消息", [(Y, "    if sessions.active():\n        return out + sessions.all_user_words()",
                                                  "    if False:\n        return out + sessions.all_user_words()")],
     [TR6 + "test_quotes_use_the_hook_record_when_hooks_run"]),
    ("X47", "自己写的脚本碰记录不拦", [(H, "        if any(mark in code for mark in SCRIPT_MARKS):\n            return SCRIPT_REASON",
                                    "        if False:\n            return SCRIPT_REASON")],
     [TR6 + "test_own_scripts_that_touch_protected_records_are_refused"]),
    ("X48", "从管道喂给 Python 的代码不算写", [(H, '\n                      + r"|\\|\\s*(?:py|python3?|pythonw)(?:\\.exe)?(?=\\s|$)", re.I)', ", re.I)")],
     [TR6 + "test_own_scripts_that_touch_protected_records_are_refused"]),
    ("X46", "原生卡上用户写的话不算用户说过的", [(SE, "            out += [p for _t, p in prompts(sid)] + answer_texts(sid)",
                                               "            out += [p for _t, p in prompts(sid)]")],
     [TR6 + "test_note_typed_on_a_native_card_counts_as_the_users_words"]),
    ("X34", "链接的目标照扫英文词", [(W, "        for x in range(a, b):\n            mask[x] = 1\n            plain[x] = 1\n    for m in _AUTOLINK_RE.finditer(text):",
                                     "        pass\n    for m in _AUTOLINK_RE.finditer(text):")],
     [TR6 + "test_link_targets_are_not_scanned_for_english_words"]),
    ("X35", "env_check 不报没有 rg", [(E, '    if not rg["present"]:\n        out["next"] += " " + RG_MISSING', '    if False:\n        out["next"] += " " + RG_MISSING')],
     [TR6 + "test_env_check_reports_rg"]),
    ("X36", "缺组件时对用户说英文名", [(E, '            PURPOSES.get(m, "跑云织的脚本") for m in checks[1]["missing"])', '            m for m in checks[1]["missing"])')],
     [TR6 + "test_env_check_names_missing_parts_by_purpose"]),
    ("X37", "资料汇编卡不显示反向检索的数", [(C, '        lines.append("- %s" % counter_line)\n        ask_lines.append(counter_line)', "        pass")],
     [TR6 + "test_dossier_card_shows_the_counter_search_counts"]),
    ("X38", "反向检索找到的全归背景也出卡", [(C, '    if bad:\n        raise Refuse(["反向检索找到的资料里', '    if False:\n        raise Refuse(["反向检索找到的资料里')],
     [TR6 + "test_counter_finds_all_filed_as_background_need_a_reason"]),
    ("X39", "反向检索不要求 found", [(C, "        out += counter_found_problems(project, cs)", "        pass")],
     [TR6 + "test_counter_search_must_list_real_cards"]),
    ("X40", "AGENTS.md 没写没信任时照旧", [("AGENTS.md", "**没信任时它根本不跑：一切照这份说明做，规矩一条不变。**", "没信任时也照样拦。")],
     [TR6 + "test_agents_md_rg_and_hooks"]),
    ("X41", "AGENTS.md 没写不要试 rg", [("AGENTS.md", "不要试 rg", "可以先试 rg")], [TR6 + "test_agents_md_rg_and_hooks"]),
    ("X42", "evidence-card 没写削弱判断的归不支持", [(".agents/skills/evidence-card/SKILL.md", "削弱核心判断任何一部分的数据，都归不支持",
                                                   "削弱核心判断的数据可以归背景")],
     [TR6 + "test_evidence_skill_states_the_counter_rule"]),
    ("X43", "hooks.json 的工具 matcher 改了", [(".codex/hooks.json",
                                              '{"matcher": "*", "hooks": [{"type": "command", "command": "py -X utf8 agent-tools/hook.py"}]}\n    ],\n    "PostToolUse"',
                                              '{"matcher": "Bash", "hooks": [{"type": "command", "command": "py -X utf8 agent-tools/hook.py"}]}\n    ],\n    "PostToolUse"')],
     [TR6 + "test_hooks_json_runs_the_hook_for_the_four_events"]),
    ("X44", "别的脚本也写确认记录", [(P, "def esc(s):", 'def _write_record():\n    run("stamp.py", ["x.md", "--approve"])\n\n\ndef esc(s):')],
     [TS + "test_approve_only_inside_card_py"]),
    ("X45", "守门脚本一开头就拉进 PyYAML", [(H, "import sessions  # noqa: E402", "import sessions  # noqa: E402\nimport yaml  # noqa: E402,F401")],
     [TR6 + "test_hook_imports_only_the_standard_library_up_front"]),
    # ---- 第七轮(10-04):只写了意见之后回数字直接算数;只写意见后的说法说怎么继续;打回重说时保留下一步
    ("Y01", "只写了意见之后回数字不算", [(C, '    if last.get("type") == "answered" and last.get("choice") is None and last.get("result") in NOTE_RESULTS:\n        return "note"',
                                        '    if False:\n        return "note"')],
     [TR7 + "test_note_then_number_confirms_the_task_plan_once"]),
    ("Y02", "明明白白选了先不确认也能再答", [(C, 'last.get("type") == "answered" and last.get("choice") is None and last.get("result")',
                                           'last.get("type") == "answered" and last.get("result")')],
     [TR7 + "test_explicit_not_yet_is_not_reopened"]),
    ("Y03", "只写了意见之后能答不止一次", [(C, '    if len(closing) != 1:\n        return None\n    last = closing[0]',
                                          '    if not closing:\n        return None\n    last = closing[0]')],
     [TR7 + "test_note_reopen_only_once"]),
    ("Y04", "只写了意见之后出过别的卡照样算它的回答", [(C, "    if reopen and latest_prepared(log) is not prepared:", "    if False:")],
     [TR7 + "test_after_note_a_newer_card_wins"]),
    ("Y05", "只写了意见之后认不出的话也当回答", [(C, '    if reopen and (shape not in ("chat", "tool") or read_reply(text, options)[0] is None):', "    if False:")],
     [TR7 + "test_after_note_other_messages_are_just_chat"]),
    ("Y06", "记用户消息时不提示只写了意见的卡", [(C, "    card, why = reopenable_card(project)", "    card, why = None, None")],
     [TR7 + "test_note_then_number_on_report_type"]),
    ("Y07", "只写了意见之后不说怎么继续(确认类)",
     [(C, '"%s还没定下来：你写的话算意见，不算确认。要按这一版定下来，直接回 1 就行；要改的话告诉我改哪里。" % doc_label(data)',
       '"%s还没定下来：你写的话算意见，不算确认。" % doc_label(data)')],
     [TR7 + "test_note_only_say_ends_with_how_to_continue"]),
    ("Y08", "只写了意见之后不列选项编号(报告类型、决定)",
     [(C, 'return "你写的我记下了。%s，直接回选项前面的数字就行：%s。" % (what, numbered_options(options))', 'return "你写的我记下了。"')],
     [TR7 + "test_note_only_say_ends_with_how_to_continue"]),
    ("Y09", "再答的那一次也认意见之前说的话",
     [(C, "        since = max(t for t in (prepared_ts(prepared), event_ts(closing[0]), 0.0) if t is not None)", "        since = None")],
     [TR7 + "test_reopen_after_note_needs_words_said_after_the_note"]),
    ("Y10", "打回重说时不提保留下一步", [(H, '"重说时保留原来要告诉用户的下一步（比如回哪个数字）%s。")', '"%s")')],
     [TR7 + "test_stop_reason_keeps_the_next_step"]),
    ("Y11", "打回时不交还说下一步的那句", [(H, "    return out[:2]\n\n\ndef on_stop(d):", "    return []\n\n\ndef on_stop(d):")],
     [TR7 + "test_stop_reason_keeps_the_next_step"]),
    ("Y12", "像是想确认还叫重新出卡", [(C, '"不改材料，说 say 里那句话，停下等用户。" % (note, confirm_label)) + reopen_next(kind),',
                                    '"重新跑 prepare 出这张卡，出卡前说 say 里那句话。" % (note, confirm_label)),')],
     [TR7 + "test_looks_like_yes_then_number_confirms_without_a_new_card"]),
    ("Y13", "改流程卡只写了意见就马上还原", [(C, '"② 没说清（例如「直接帮我确认吧」，或者问了个问题）：先别还原，',
                                           '"② 没说清（例如「直接帮我确认吧」，或者问了个问题）：也马上还原，')],
     [TR7 + "test_flow_change_note_waits_then_number_confirms"]),
    ("Y14", "改流程已经还原了还说重新准备了卡", [(C, '        if kind == "flow_change" and not problem and not yzlib.flow_change_pending(meta, body):', "        if False:")],
     [TR7 + "test_flow_change_reverted_after_note_says_so"]),
    ("Y15", "回答记录不带到毫秒的时刻", [(C, 'base = {"at": yzlib.now_iso(), "ts": time.time(), "card_id": card_id,', 'base = {"at": yzlib.now_iso(), "card_id": card_id,')],
     [TR7 + "test_answer_events_carry_a_fine_timestamp"]),
    ("Y16", "yunzhi-card 没写只写了意见之后", [(".agents/skills/yunzhi-card/SKILL.md", "**只写了意见之后**", "**意见之后**")],
     [TR7 + "test_card_skill_and_agents_md_cover_the_note_reopen"]),
    ("Y17", "AGENTS.md 没写只写了意见之后", [("AGENTS.md", "卡上只写了意见、没选选项之后也一样", "卡上写了意见之后")],
     [TR7 + "test_card_skill_and_agents_md_cover_the_note_reopen"]),
    ("Y18", "只写了意见不给照改时的说法", [(C, '"say": note_only_say(kind, data, prepared.get("options")), "say_revise": note_revise_say(kind, data)}, []',
                                         '"say": note_only_say(kind, data, prepared.get("options"))}, []')],
     [TR7 + "test_note_only_say_ends_with_how_to_continue"]),
    ("Y19", "卡收起之后也只认收起之后说的话", [(C, '    if reopen == "note":\n        since = max(', '    if reopen:\n        since = max(')],
     [TR7 + "test_number_typed_while_the_card_was_open_still_answers_after_a_collapse"]),
    # ---- 第八轮(10-04,开着 hooks 的命令行全程试跑之后)
    ("Z01", "全角逗号后面跟数字不算隔开", [(C, 'HARD_SEPARATORS = "，；："', 'HARD_SEPARATORS = ""')],
     [TR8 + "test_fullwidth_separator_then_anything_is_option_plus_note", TR8 + "test_confirm_card_fullwidth_comma_then_a_year"]),
    ("Z02", "半角逗号后面跟数字也当隔开(千分位、列举被当成选项)",
     [(C, "        if after[:1].isdigit():\n            return False, None", "        if False:\n            return False, None")],
     [TR8 + "test_halfwidth_comma_enumeration_and_decimals_stay_unrecognised"]),
    ("Z03", "反向检索归成背景的不逐条显示理由", [(C, '                lines.append("  - %s" % row)', "                pass")],
     [TR8 + "test_counter_finds_filed_as_background_each_need_a_reason_on_the_card"]),
    ("Z04", "下载被拒(403)记成出错", [(F, "        if e.code in (401, 403, 429):", "        if e.code in (401, 429):")],
     [TR8 + "test_save_url_failures_are_recorded_in_the_five_states"]),
    ("Z05", "下载没有大小上限", [(F, "            if length and length.isdigit() and int(length) > cap:", "            if False:"),
                            (F, "                if size > cap:", "                if False:")],
     [TR8 + "test_save_url_size_cap_and_unsupported_types"]),
    ("Z06", "不收的类型也照存", [(F, "    if ext is None:\n        raise NotAccepted(", "    if False:\n        raise NotAccepted(")],
     [TR8 + "test_save_url_size_cap_and_unsupported_types"]),
    ("Z07", "没下载成不记五态", [(F, '        rec = add(project, url, f.state, "下载：%s" % f.detail)', "        rec = None")],
     [TR8 + "test_save_url_failures_are_recorded_in_the_five_states"]),
    ("Z08", "save 还要先自己下载好文件", [(F, '    v.add_argument("--file")\n', '    v.add_argument("--file", required=True)\n')],
     [TR8 + "test_save_url_cli_needs_no_file"]),
    ("Z09", "守门脚本不拦给复核助手发消息", [(H, "    if collab_message_tool(low):\n        return refuse(d, name, REVIEW_MSG_REASON)",
                                    "    if False:\n        return refuse(d, name, REVIEW_MSG_REASON)")],
     [TR8 + "test_hook_denies_messaging_the_reviewer"]),
    ("Z10", "守门脚本连等复核助手也拦", [(H, 'COLLAB_ALLOWED = ("spawn_agent", "wait_agent", "list_agents")', 'COLLAB_ALLOWED = ("spawn_agent",)')],
     [TR8 + "test_hook_lets_waiting_and_other_tools_through"]),
    ("Z11", "交付时刻取写记录的时刻", [(C, '        record = {"delivered_at": at or yzlib.now_iso(),', '        record = {"delivered_at": yzlib.now_iso(),')],
     [TR8 + "test_delivered_at_is_the_moment_of_the_answer"]),
    ("Z12", "没取到的资料按次数数", [(F, "    seen = set()\n    for e in entries(project):", "    seen = []\n    for e in entries(project):"),
                              (F, "            seen.add((url, st))", "            seen.append((url, st))")],
     [TR8 + "test_failed_fetches_are_counted_per_source"]),
    ("Z13", "AGENTS.md 没写选项框只发准备好的卡", [("AGENTS.md", "**选项框只用来发 `card.py prepare` 准备好的卡**", "选项框也可以拿来问开场问题")],
     [TR8 + "test_opening_questions_are_plain_chat_not_the_card_tool"]),
    ("Z14", "yunzhi 没写开场问题是普通对话", [(".agents/skills/yunzhi/SKILL.md", "**`say` 那句和开场「一次问完」的问题写在同一条回复里，问题就是普通对话**",
                                         "开场问题可以用选项框问")],
     [TR8 + "test_opening_questions_are_plain_chat_not_the_card_tool"]),
    ("Z15", "交付前检查不拦引用了、探测没打开的来源", [(CC, "        if unmarked or unreached:", "        if unmarked:")],
     [TR8 + "test_cited_source_the_probe_could_not_open_blocks_until_marked_read"]),
    ("Z16", "没读过的也能记成读过", [(L, "    if unread:\n        # 第八轮", "    if False:\n        # 第八轮")],
     [TR8 + "test_cited_source_the_probe_could_not_open_blocks_until_marked_read",
      TR3 + "test_liveness_offline_is_unchecked_and_web_tool_pages_stay_reachable"]),
    ("Z17", "探测完不说哪几条引用了却没打开", [(L, '    if unreached:\n        out["cited_unreached"]', '    if False:\n        out["cited_unreached"]')],
     [TR8 + "test_liveness_run_points_out_cited_unreached_sources"]),
    ("Z18", "交付后不清 .yz-tmp/<项目名>/", [(C, "        if yzlib.clean_agent_tmp(project):", "        if False:")],
     [TR8 + "test_delivery_cleans_the_agents_own_tmp_folder"]),
    ("Z19", "note-user 先记的那一条不补标记", [(C, "    i, obj = unmarked[-1]               # note-user 先记的那一条:补上标记",
                                       "    return True\n    i, obj = unmarked[-1]")],
     [TR8 + "test_note_only_reply_is_logged_once_with_via_and_card"]),
    ("Z20", "文字卡上回的「跳过」不带标记", [(C, "        if project and words in SKIP_WORDS:", "        if False:")],
     [TR8 + "test_typed_skip_is_logged_once_with_via_and_card"]),
    ("Z21", "跳过之后 note-user 再记一遍", [(C, 'last.get("type") in ("answered", "skipped", "changed", "error")',
                                     'last.get("type") in ("answered", "changed", "error")')],
     [TR8 + "test_typed_skip_is_logged_once_with_via_and_card"]),
    ("Z22", "evidence-card 没写拿来削弱判断的就是不支持", [(".agents/skills/evidence-card/SKILL.md", "成稿里要拿来削弱判断的资料，立场就是不支持",
                                                 "成稿里的资料照常标")],
     [TR8 + "test_evidence_skill_says_material_used_to_weaken_is_counter"]),
    ("Z23", "AGENTS.md 没写不用 Invoke-WebRequest 下载", [("AGENTS.md", "不用 Invoke-WebRequest、curl、wget 下载", "也可以用 Invoke-WebRequest 下载")],
     [TR8 + "test_docs_say_download_with_fetches_not_invoke_webrequest"]),
    ("Z24", "cite-trace 没写起了复核助手就不再发消息", [(".agents/skills/cite-trace/SKILL.md", "**起了之后不再给它发消息**", "起了之后可以接着给它发消息")],
     [TR8 + "test_docs_say_only_spawn_and_wait"]),
    ("Z25", "review.py start 没说不再给复核助手发消息", [(R, "；起了之后不再给它发消息（不用 send_message、followup_task，也不打断它）。", "。")],
     [TR8 + "test_review_start_says_not_to_message_the_reviewer"]),
]


def sha(path):
    with io.open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def make_copy(base):
    ignore = shutil.ignore_patterns("__pycache__", ".pytest_cache", "fixtures", ".yz-tmp")
    for name in COPY:
        src = os.path.join(ROOT, name)
        dst = os.path.join(base, name)
        if os.path.isdir(src):
            shutil.copytree(src, dst, ignore=ignore)
        else:
            shutil.copy2(src, dst)


def run_tests(base, nodes):
    env = dict(os.environ, YUNZHI_FIXTURES=FIXTURES, PYTHONDONTWRITEBYTECODE="1", PYTHONIOENCODING="utf-8")
    env.pop("YUNZHI_CARDS", None)
    env.pop("YUNZHI_PROJECTS", None)
    env.pop("CODEX_THREAD_ID", None)        # 在 Codex 的对话里跑时:测试一律从「守门脚本没跑」开始
    env.pop("CODEX_SESSION_ID", None)
    p = subprocess.run([sys.executable, "-X", "utf8", "-B", "-m", "pytest", "-q", "-x", "-p", "no:cacheprovider"] + nodes,
                       cwd=base, env=env, capture_output=True)
    tail = p.stdout.decode("utf-8", "replace").strip().splitlines()
    return p.returncode, (tail[-1] if tail else "")


def main(argv):
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass
    wanted = set(argv[1:])
    todo = [m for m in MUTATIONS if not wanted or m[0] in wanted]
    tmp_root = os.path.join(ROOT, ".yz-tmp")
    os.makedirs(tmp_root, exist_ok=True)
    base = os.path.join(tmp_root, "mutation-%s" % secrets.token_hex(4))
    os.makedirs(base)
    results = []
    try:
        make_copy(base)
        all_nodes = sorted({n for m in todo for n in m[3]})
        code, last = run_tests(base, all_nodes)
        print("基线(没改坏):%s · %s" % ("全绿" if code == 0 else "不绿!", last))
        if code != 0:
            return 2
        for mid, what, edits, nodes in todo:
            originals = {}
            missing = []
            for rel, old, new in edits:
                path = os.path.join(base, *rel.split("/"))
                if path not in originals:
                    with io.open(path, encoding="utf-8", newline="") as f:
                        originals[path] = f.read()
                with io.open(path, encoding="utf-8", newline="") as f:
                    text = f.read()
                if old not in text:
                    missing.append(rel)
                    continue
                with io.open(path, "w", encoding="utf-8", newline="") as f:
                    f.write(text.replace(old, new, 1))
            if missing:
                results.append((mid, what, "改坏失败:原文不在 %s" % ", ".join(missing), False))
            else:
                code, last = run_tests(base, nodes)
                results.append((mid, what, ("变红 · " if code != 0 else "仍然绿 · ") + last, code != 0))
            for path, text in originals.items():
                with io.open(path, "w", encoding="utf-8", newline="") as f:
                    f.write(text)
        # 还原核对:拷贝里每个改过的文件与工作区原件逐字节相同
        for _mid, _what, edits, _nodes in todo:
            for rel, _o, _n in edits:
                assert sha(os.path.join(base, *rel.split("/"))) == sha(os.path.join(ROOT, *rel.split("/"))), rel
        code, last = run_tests(base, all_nodes)
        print("还原之后:%s · %s" % ("全绿" if code == 0 else "不绿!", last))
    finally:
        shutil.rmtree(base, ignore_errors=True)
    width = max(len(w) for _m, w, _r, _ok in results)
    for mid, what, res, ok in results:
        print("%s %s %s  %s" % ("✓" if ok else "✗", mid, what.ljust(width), res))
    caught = sum(1 for r in results if r[3])
    print("变红 %d / %d" % (caught, len(results)))
    return 0 if caught == len(results) else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
